### ISSUE TITLE
Remove history before some day

### ISSUE THREAD

**Issue by avently** [andy-portmen/ecleaner#1]
Hello. Thank you for this extension. 
Can you make an option to remove all data BEFORE some date? For now you added an option to remove new data - one week ago and newer. But what if i need "delete all old staff before last week". I do not care about history or cookies that i'm not using a week or a month. But i do care about new cookies from today or yesterday. Is this possible?

**Comment by andy-portmen** [comment]
I am trying to skip having options page. But this seems like a must have. I'll see what I can do

**Comment by andy-portmen** [comment]
![screen shot 2017-08-21 at 12 19 39 pm](https://user-images.githubusercontent.com/6779535/29508763-08a33ada-866b-11e7-933a-820d26b06b94.png)

**Comment by avently** [comment]
@andy-portmen maybe I didn't understand something, but how this commit fixes the issue? You showed that you have added an option to remove a data for a custom selected time period. This is not the same as what we are discussing here. I asked about deletion of all data before some date, for example, before last week. It means that  all new data from current week will be safe and will remain but all data before last week should be deleted.

**Comment by andy-portmen** [comment]
I must have misunderstood this then!
