### ISSUE TITLE
scrollbars caused by doorhanger size

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [andy-portmen/ecleaner#3]
Using FF54 Desktop. As you can see, this is rather annoying. Suggestion to change the `Proceeding will:` to `Proceeding will delete recent:` and strip the repetitive `Delete recent`. This will release some width for smaller devices which is a bonus.

![ecleanerscrollbars](https://user-images.githubusercontent.com/16656956/28493934-3becea66-6f74-11e7-8c39-a6bb4eb838d1.png)

**Comment by Thorin-II** [comment]
Also a suggestion to group the Chrome & Opera items together, and even to not display (and auto-uncheck them) them in Firefox

**Comment by andy-portmen** [comment]
Applied to 0.1.3. If you still get the scrollbars please reopen.
