### ISSUE TITLE
"Forget!" action never notifies it has completed

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [andy-portmen/ecleaner#4]
I never get any visual notification that cleaning finished .. it just says `Please wait ...` and never "completes".

Note: FF54. I used the default settings and I virtually had nothing to clear except History ave a couple of items (I have services workers disabled, forms & downloads were already empty, I only use memory cache, indexedDB is disabled, dom storage should have been empty, I have no plugins, etc).

![ecleanerneverends](https://user-images.githubusercontent.com/16656956/28493978-431a53ae-6f75-11e7-98bf-251f39b663da.png)

**Comment by andy-portmen** [comment]
Fixed! Thanks
