### ISSUE TITLE
Add link to AMO on add0n.com homepage

### ISSUE THREAD

**Issue by Atavic** [andy-portmen/ecleaner#7]
add0n.com/ecleaner page has no link for Firefox on top right.

Please provide direct link to:
https://addons.mozilla.org/firefox/addon/ecleaner-forget-button/

**Comment by Thorin-II** [comment]
strip the en-US part and the page will load your browser language version
i.e - https://addons.mozilla.org/firefox/addon/ecleaner-forget-button/

**Comment by andy-portmen** [comment]
done
