### ISSUE TITLE
It never completes (and also doesn't delete anything)

### ISSUE THREAD

**Issue by mario98** [andy-portmen/ecleaner#8]
I'm using Firefox 52 ESR and for me the addon doesn't work. I have a similar issue mentioned in #4 but for me it actually never deletes anything. So it displays "Please wait..." forever and my data is not deleted.

Example use case:
Select "Cookies" only and "From day one". Then click "Forget!".  It displays "Please wait..." forever. If you just close the popup and go to preferences > privacy > show cookies, you will see that cookies were not deleted.

Addon version 0.1.4 from AMO.

**Comment by andy-portmen** [comment]
Do you still have this issue? If so please check the error console of your browser. Most likely this is some internal error in WebExtension core.

**Comment by mario98** [comment]
Yes, and here is what is says:

    chrome.browsingData is undefined index.js:47
	<anonym> moz-extension://429f811e-2d1a-4e3d-b62d-df34c229deb8/data/panel/index.js:47:5
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:71:14
	runSafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:133:38
	bound runSafeWithoutClone self-hosted:917:17
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:312:13

(Now version 0.1.5)

**Comment by andy-portmen** [comment]
> chrome.browsingData is undefined

Either you are using an old version of Firefox that still does not support `browsingData` or your Firefox profile is damaged.

**Comment by mario98** [comment]
Yup, [doc](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData) says it's Firefox 53+. Too bad.

Can you please set min version to 53 then? This will avoid that people waste their time with an addon that's known to not work with their browser.
