### ISSUE TITLE
FR: Allow auto-cleaning on browser termination

### ISSUE THREAD

**Issue by Gitoffthelawn** [andy-portmen/ecleaner#9]
Hello Andy. :)

Can you add an option to perform the cleaning when the browser terminates (well, obviously, just before it terminates)?

**Comment by andy-portmen** [comment]
As far as I know, there is no event to listen for that reliably calls your observer when the browser is about to exit. Note that to have no effect on the browser performance, this extension uses "event page" background script; https://github.com/andy-portmen/ecleaner/blob/master/manifest.json#L21 (this is not yet supported on Firefox!)

This means there is no persistent background script at all. We need to rely on the Chrome's runtime events and there is no exit event as far as I can tell

**Comment by andy-portmen** [comment]
So in the latest dev version, the extension performs the last cleaning when there is no browser window open. This is the closest to what you are looking for. Note that the option is disabled by default and can be turned on from the options page.

Also, note that you need to perform at least one manual cleaning from the popup so that the extension could record whatever you want to be cleaned.

**Comment by Gitoffthelawn** [comment]
Thanks Andy!

Ah, the (current) limitations of WebExtensions API.

Just FYI, this extension can delete everything on Firefox termination: https://addons.mozilla.org/firefox/addon/clickclean/

Of course, it does not use WebExtensions API.

> Also, note that you need to perform at least on manual cleaning from the popup so that the extension could record what even you want to be cleaned.

Hmmm.... can an options page allow this be set ahead of time?

**Comment by andy-portmen** [comment]
I meant "one manual cleaning". This is to know what is the preferred cleaning preferences of the user.

**Comment by Gitoffthelawn** [comment]
I figured that's what you meant.  I wonder if you can create an options menu to specify what should be cleaned on termination so that one manual cleaning need not be performed.

**Comment by andy-portmen** [comment]
Yes, you can now set whatever you prefer to be cleaned on exit from the panel without actually performing the cleaning 

![screen shot 2017-09-24 at 11 09 21 am](https://user-images.githubusercontent.com/6779535/30780495-f3b88936-a118-11e7-816f-5b632a77b2ff.png)

**Comment by Gitoffthelawn** [comment]
Thanks!

BTW, does it really clean IndexedDB Databases?  I thought that wasn't possible (yet) with WebExtensions.

**Comment by andy-portmen** [comment]
IndexedDB is removed from the latest release (only for FF)

**Comment by Gitoffthelawn** [comment]
I think it is on the Mozilla schedule to make IndexedDB clearable... perhaps for version 58.

**Comment by andy-portmen** [comment]
since FF throws error, I had to remove these types.
https://github.com/andy-portmen/ecleaner/blob/master/data/panel/index.js#L9-L11

Let me know when it is supported and I'll remove it from the list.

**Comment by Gitoffthelawn** [comment]
I created a new issue for this new topic: https://github.com/andy-portmen/ecleaner/issues/10
